[package]
name = "learn-anything"
version = "0.0.0"
description = "Learn Anything"
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = [ "dialog-all", "fs-remove-file", "fs-remove-dir", "fs-rename-file", "fs-exists", "fs-create-dir", "fs-read-dir", "fs-write-file", "fs-read-file", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
log_macro = "0.1.6"
tauri_plugin_deep_link = "0.1.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
